# Generated by Django 4.2.4 on 2024-06-24 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askbot', '0027_populate_analytics_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_questions', models.PositiveIntegerField()),
                ('num_answers', models.PositiveIntegerField()),
                ('num_upvotes', models.PositiveIntegerField()),
                ('num_downvotes', models.PositiveIntegerField()),
                ('question_views', models.PositiveIntegerField()),
                ('time_on_site', models.DurationField()),
                ('date', models.DateField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupDailySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_questions', models.PositiveIntegerField()),
                ('num_answers', models.PositiveIntegerField()),
                ('num_upvotes', models.PositiveIntegerField()),
                ('num_downvotes', models.PositiveIntegerField()),
                ('question_views', models.PositiveIntegerField()),
                ('time_on_site', models.DurationField()),
                ('date', models.DateField(db_index=True)),
                ('num_users', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askbot.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
