# Generated by Django 4.2.4 on 2024-06-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0028_dailyusersummary_dailygroupsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='visibility',
            field=models.SmallIntegerField(choices=[(0, 'Visible to administrators'), (1, 'Visible to moderators and administrators'), (2, 'Visible to own members, moderators and administrators'), (3, 'Visible to everyone')], default=3),
        ),
    ]
