# Generated by Django 4.2.4 on 2024-07-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0029_group_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='summarized',
            field=models.BooleanField(default=False, help_text='True if the event is included into a summary'),
        ),
        migrations.AddField(
            model_name='group',
            name='used_for_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailygroupsummary',
            name='summarized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyusersummary',
            name='summarized',
            field=models.BooleanField(default=False),
        ),
    ]
