# Generated by Django 4.2.4 on 2024-07-28 21:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askbot', '0031_session_last_summarized_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyUserSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_questions', models.PositiveIntegerField(default=0)),
                ('num_answers', models.PositiveIntegerField(default=0)),
                ('num_upvotes', models.PositiveIntegerField(default=0)),
                ('num_downvotes', models.PositiveIntegerField(default=0)),
                ('question_views', models.PositiveIntegerField(default=0)),
                ('time_on_site', models.DurationField(default=datetime.timedelta(0))),
                ('summarized', models.BooleanField(default=False)),
                ('hour', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HourlyGroupSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_questions', models.PositiveIntegerField(default=0)),
                ('num_answers', models.PositiveIntegerField(default=0)),
                ('num_upvotes', models.PositiveIntegerField(default=0)),
                ('num_downvotes', models.PositiveIntegerField(default=0)),
                ('question_views', models.PositiveIntegerField(default=0)),
                ('time_on_site', models.DurationField(default=datetime.timedelta(0))),
                ('summarized', models.BooleanField(default=False)),
                ('hour', models.DateTimeField(db_index=True)),
                ('num_users', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askbot.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
