# Generated by Django 4.2.4 on 2024-07-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0032_hourlyusersummary_hourlygroupsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygroupsummary',
            name='num_users_added',
            field=models.PositiveIntegerField(default=0, help_text='Number of users added to the group during the day'),
        ),
        migrations.AddField(
            model_name='hourlygroupsummary',
            name='num_users_added',
            field=models.PositiveIntegerField(default=0, help_text='Number of users added to the group during the hour'),
        ),
        migrations.AlterField(
            model_name='dailygroupsummary',
            name='num_users',
            field=models.PositiveIntegerField(default=0, help_text='Number of users in the group by the end of the day'),
        ),
        migrations.AlterField(
            model_name='hourlygroupsummary',
            name='num_users',
            field=models.PositiveIntegerField(default=0, help_text='Number of users in the group by the end of the hour'),
        ),
    ]
