# Generated by Django 4.2.4 on 2024-10-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0033_dailygroupsummary_num_users_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.SmallIntegerField(choices=[(1, 'registered'), (2, 'logged in'), (3, 'logged out'), (4, 'question viewed'), (5, 'answer viewed'), (6, 'upvoted'), (7, 'downvoted'), (8, 'canceled vote'), (9, 'asked'), (10, 'answered'), (11, 'commented question'), (12, 'commented answer'), (13, 'retagged question'), (14, 'searched')]),
        ),
    ]
