name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.7]

#    services:
#      postgres:
#        # image should match heroku and/or docker-compose.yaml
#        image: postgres:13.6
#        env: # must match with settings from $DJANGO_SETTINGS_MODULE
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_DB: github-actions
#        ports:
#          - 5432:5432 # exposing 5432 port for application to use
#        # needed because the postgres container does not provide a healthcheck
#        options: >-
#          --health-cmd pg_isready --health-interval 10s
#          --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools-rust
        python setup.py install
        pip install -r requirements-tests.txt
        cat askbot_setup_test_inputs.txt | askbot-setup
        pwd
        ls -l
    - name: Run Tests
      run: |
        pwd
        ls -d askbot_site
        cd askbot_site
        ln -s ../askbot/tests .
        python manage.py test tests.test_forms
#      env:
#        # Variables for unit tests
#        DJANGO_SETTINGS_MODULE: settings
#        # For Django encryption
#        SECRET_KEY: some_value
#        RECAPTCHA_PRIVATE_KEY: some_key
#        # must match postgres service above
#        DATABASE_URL: postgres://postgres:postgres@localhost:5432/default
