/* Auto-generated by bin/sync_sanitize_config.py — do not edit */
/* eslint-disable */
var PURIFY_CONFIG = {
  ALLOWED_TAGS: ["a", "b", "blockquote", "br", "code", "dd", "del", "details", "dl", "dt", "em", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "i", "img", "input", "kbd", "li", "ol", "p", "pre", "s", "span", "strike", "strong", "sub", "summary", "sup", "table", "tbody", "td", "th", "thead", "tr", "ul"],
  ALLOWED_ATTR: ["alt", "checked", "cite", "class", "colspan", "datetime", "disabled", "href", "rowspan", "src", "title", "type"]
};

var ALLOWED_ATTR_MAP = {
  "a": [
    "href",
    "title"
  ],
  "blockquote": [
    "cite"
  ],
  "code": [
    "class"
  ],
  "del": [
    "cite",
    "datetime"
  ],
  "img": [
    "alt",
    "src"
  ],
  "input": [
    "checked",
    "disabled",
    "type"
  ],
  "li": [
    "class"
  ],
  "span": [
    "class"
  ],
  "td": [
    "colspan",
    "rowspan"
  ],
  "th": [
    "colspan",
    "rowspan"
  ],
  "ul": [
    "class"
  ]
};
